import CryptoKit
import Foundation

public struct ContentReference: Codable, Equatable, Sendable {
    public let digest: String
    public let byteCount: Int

    public init(digest: String, byteCount: Int) {
        self.digest = digest
        self.byteCount = byteCount
    }
}

public enum ContentStoreError: Error, Equatable, Sendable {
    case invalidDigest
    case missingContent(String)
    case digestMismatch(expected: String, actual: String)
}

/// A private, content-addressed store for exact restoration and generated bytes.
public final class ContentAddressedStore: @unchecked Sendable {
    public let rootURL: URL

    private let fileManager: FileManager

    public init(rootURL: URL, fileManager: FileManager = .default) throws {
        self.rootURL = rootURL
        self.fileManager = fileManager
        try fileManager.createDirectory(at: rootURL, withIntermediateDirectories: true)
        try setUserOnlyPermissions(at: rootURL, permissions: 0o700)
    }

    public func put(_ data: Data) throws -> ContentReference {
        let digest = Self.digest(of: data)
        let destination = contentURL(for: digest)
        let directory = destination.deletingLastPathComponent()
        try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)
        try setUserOnlyPermissions(at: directory, permissions: 0o700)

        if fileManager.fileExists(atPath: destination.path) {
            let existing = try Data(contentsOf: destination)
            guard Self.digest(of: existing) == digest else {
                throw ContentStoreError.digestMismatch(expected: digest, actual: Self.digest(of: existing))
            }
            try setUserOnlyPermissions(at: destination, permissions: 0o600)
            return ContentReference(digest: digest, byteCount: existing.count)
        }

        let temporary = directory.appendingPathComponent(".\(digest).\(UUID().uuidString).tmp")
        try data.write(to: temporary, options: [.atomic])
        try setUserOnlyPermissions(at: temporary, permissions: 0o600)
        do {
            try fileManager.moveItem(at: temporary, to: destination)
        } catch {
            if fileManager.fileExists(atPath: destination.path) {
                try? fileManager.removeItem(at: temporary)
            } else {
                try? fileManager.removeItem(at: temporary)
                throw error
            }
        }
        try setUserOnlyPermissions(at: destination, permissions: 0o600)
        return ContentReference(digest: digest, byteCount: data.count)
    }

    public func get(_ reference: ContentReference) throws -> Data {
        guard Self.isValidDigest(reference.digest) else {
            throw ContentStoreError.invalidDigest
        }
        let url = contentURL(for: reference.digest)
        guard fileManager.fileExists(atPath: url.path) else {
            throw ContentStoreError.missingContent(reference.digest)
        }
        let data = try Data(contentsOf: url)
        let actual = Self.digest(of: data)
        guard actual == reference.digest else {
            throw ContentStoreError.digestMismatch(expected: reference.digest, actual: actual)
        }
        guard data.count == reference.byteCount else {
            throw ContentStoreError.digestMismatch(expected: reference.digest, actual: actual)
        }
        return data
    }

    public func fileURL(for reference: ContentReference) throws -> URL {
        guard Self.isValidDigest(reference.digest) else {
            throw ContentStoreError.invalidDigest
        }
        return contentURL(for: reference.digest)
    }

    public static func digest(of data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    private func contentURL(for digest: String) -> URL {
        rootURL
            .appendingPathComponent(String(digest.prefix(2)), isDirectory: true)
            .appendingPathComponent(digest)
    }

    private static func isValidDigest(_ digest: String) -> Bool {
        digest.count == 64 && digest.allSatisfy { $0.isHexDigit }
    }

    private func setUserOnlyPermissions(at url: URL, permissions: Int) throws {
        try fileManager.setAttributes([.posixPermissions: permissions], ofItemAtPath: url.path)
    }
}
